name: 自动同步上游 MoonTVPlus

on:
  schedule:
    # 每天 UTC 18:00，即北京时间凌晨 02:00
    - cron: '0 18 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: 同步最新代码

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          upstream_sync_repo: mtvpls/MoonTVPlus
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          test_mode: false
          # 如果上游仓库是私有的，才需要下面这一行
          # upstream_repo_access_token: ${{ secrets.UPSTREAM_REPO_ACCESS_TOKEN }}

      - name: Check for value changes
        if: steps.sync.outputs.has_new_commits == 'true'
        run: echo "同步成功，已合并 mtvpls 的最新修改！"
